### PR TITLE
Updated readme to include Hackbot commands

### PR DESCRIPTION
**Pull request by andrewseward**

### CODE REVIEW

**Comment by Codesleuth** [comment]
I think you could format these a little better!

e.g.

<pre>
##Set your team's motto
'@Hackbot our motto is We are the bestest'
</pre>

<pre>
## Set your team's motto
`@hackbot our motto is We are the bestest`
</pre>

**Comment by andrewseward** [comment]
U WOT M8

I googled how to write Markdown and everything.

**Comment by nick599** [comment]
Is there sanitization of input for string searching? Otherwise it's a potential attack vector and risk

**Comment by Codesleuth** [comment]
Such as how? Feel free to review how it's done https://github.com/TechNottingham/Hack24-API/blob/master/src/server/routes/teams.ts#L45
And here's how the bot includes the search term in a request https://github.com/TechNottingham/hubot-hackbot/blob/master/src/client.ts#L210

**Review by Codesleuth — APPROVED** [review]
Yep this is fine.

**Comment by nick599** [comment]
I like the EscapeForRegExp function :)

**Pull request merged**
