### PR TITLE
@hackbot kick @username from my team

### LINKED ISSUE #3: @hackbot kick @username from my team
Remove the user specified by `@username` from the user's team. The API supports deleting team members with the following sample request:

``` http
DELETE /team/some-team-name/members HTTP/1.1
Content-Type: application/vnd.api+json

{
  "data": [{
    "type": "users",
    "id": "slackusername"
  }]
}
```

Successful requests respond with:

``` http
HTTP/1.1 204 No Content
```

Failed requests respond with:

``` http
HTTP/1.1 400 Bad Request
Content-Type: application/vnd.api+json

{
  "errors": [{
    "status": "400",
    "title": "Bad request."
  }]
}
```

Only attendees authenticating with the hackbot password (`HACKBOT_API_PASSWORD` env. variable) can kick a user from a team. Ideally, only users _within_ the team should be able to make this request, but this is not a problem since this is implied from the request itself.

### PR DESCRIPTION
**Pull request by hawx**
Fixes #3, hopefully.

### CODE REVIEW

**Comment by Codesleuth** [comment]
Honestly i think this is a bad feature. It'll lead to abuse and arguments.

**Comment by andrewseward** [comment]
Maybe, maybe not. Let's see :)

**Comment by hawx** [comment]
I was just pushing this since it has been on my laptop for months.

**Comment by Codesleuth** [comment]
Yea i noticed the test style was a bit old :-D

**Comment by hawx** [comment]
Close this if you don't want it.

**Pull request closed without merging**
